class HyperParameter():
    EPOCH = 10
    BATCH_SIZE = 64
    RESIZE = (192,256) #(96,128)
    LOG_INTERVAL =20
    TRAIN_IMAGE_DIR = '/opt/ml/input/data/train/images'
#    TRAIN_IMAGE_DIR = '/opt/ml/input_removal/train/images'
    TRAIN_CSV_DIR = '/opt/ml/input/data/train/train.csv'
    TEST_IMAGE_DIR = '/opt/ml/input/data/eval/images'
#    TEST_IMAGE_DIR = '/opt/ml/input_removal/eval'
    TEST_CSV_DIR = '/opt/ml/input/data/eval/info.csv'
    SAVE_DIR = '/opt/ml/seperate_model/seperate7/'
    SAVE_DIR2 = '/opt/ml/seperate_model/seperate6/'
    SEED = 42
    LEARNING_RATE = 1e-4
    VALIDATION_RATIO = 0.2
    NUM_CLASS=18
    NUM_MASK_CLASS=3
    NUM_GENDER_CLASS=2
    NUM_AGE_CLASS=3
